AWSTemplateFormatVersion: '2010-09-09'
Description: 'Template for AWS Backup'

Metadata: 
  # Control the UI display when running this template from the AWS Management Console:
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - Label: 
          default: "Parent Stacks"
        Parameters: 
          - ParentKMSStackName
          - ParentIAMStackName
      - Label:
          default: "Parameters"
        Parameters:
          - Prefix
          - Cron

Parameters:
  Prefix:
    Type: String
    Default: "kh-paloma-m01"
    Description:  The prefix to use for the resource name.  This is used to create unique resource names. 
  Cron:
    Description: Time to do backup(cron)
    Type: String
    Default: cron(0 18 * * ? *)
  ParentKMSStackName:
    Description: Name of an active CloudFormation stack that contains the KMS resources.
    Type: String
    Default: "KMS2"
    ConstraintDescription: Must be the name of an existing CloudFormation stack.
  ParentIAMStackName:
    Type: String
    Default: "IAM1"
    Description: Name of the stack where IAM is created
    ConstraintDescription: Must be the name of an existing CloudFormation stack.

Resources:

  BackupVault:
    Type: "AWS::Backup::BackupVault"
    Properties:
      BackupVaultName: !Sub ${Prefix}-backup-vault

  BackupPlan:
    Type: AWS::Backup::BackupPlan
    Properties: 
      BackupPlan: 
        BackupPlanName: !Sub ${Prefix}-backup-plan01
        BackupPlanRule: 
          - RuleName: !Sub ${Prefix}-backup-rule01
            TargetBackupVault: !Ref BackupVault
            ScheduleExpression: !Ref Cron
            CompletionWindowMinutes: 300
            StartWindowMinutes: 60
            Lifecycle:
              DeleteAfterDays: 2

  BackupSelection:
    Type: AWS::Backup::BackupSelection
    Properties:
      BackupPlanId: !Ref BackupPlan
      BackupSelection:
        SelectionName: !Sub ${Prefix}-backup-plan01
        IamRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/service-role/AWSBackupDefaultServiceRole"
        ListOfTags:
         -
           ConditionType: "STRINGEQUALS"
           ConditionKey: "Backup"
           ConditionValue: !Sub ${Prefix}-backup-rule01