AWSTemplateFormatVersion: 2010-09-09

Metadata: 
  # Control the UI display when running this template from the AWS Management Console:
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - Label:
          default: "Parameters"
        Parameters:
          - Prefix

Parameters:
  Prefix:
    Type: String
    Default: "kh-paloma-m01"
    Description:  The prefix to use for the resource name.  This is used to create unique resource names. 

Resources:

  EC2IAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Prefix}-role-ec2"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
        - "arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy"
      Tags:
        - Key: Name
          Value: !Sub ${Prefix}-role-ec2

  TrailIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub "${Prefix}-role-trail"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: AssumeRole1
          Effect: Allow
          Principal:
            Service: 'cloudtrail.amazonaws.com'
          Action: 'sts:AssumeRole'
      Policies:
      - PolicyName: 'cloudtrail-policy'
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - 'logs:CreateLogStream'
            - 'logs:PutLogEvents'
            Resource: '*'
      Tags:
        - Key: Name
          Value: !Sub ${Prefix}-role-trail

  ConfigIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Prefix}-role-config"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - config.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
      - 'arn:aws:iam::aws:policy/service-role/AWS_ConfigRole'
      Policies:
        - PolicyName: ConfigCustomPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetBucketAcl"
                  - "s3:PutObject"
                  - "sns:Publish"
                Resource: '*'
      Tags:
        - Key: Name
          Value: !Sub ${Prefix}-role-config

  BackupIAMrole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSBackupDefaultServiceRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Action: sts:AssumeRole
          Principal:
            Service: backup.amazonaws.com
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForBackup
      - arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForRestores
      Path: "/service-role/"

Outputs:
  EC2IAM:
    Description: IAM for EC2
    Value: !Ref EC2IAMRole
    Export:
      Name: !Sub ${AWS::StackName}-ROLE-Ec2
  TrailIAM:
    Description: IAM for CloudTrail
    Value: !Ref TrailIAMRole
    Export:
      Name: !Sub ${AWS::StackName}-ROLE-Trail
  ConfigIAM:
    Description: IAM for AWS Config
    Value: !Ref ConfigIAMRole
    Export:
      Name: !Sub ${AWS::StackName}-ROLE-Config
  TrailIAMArn:
    Description: IAM for AWS CloudTrail
    Value: !GetAtt TrailIAMRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-ROLE-TrailArn  
  ConfigIAMArn:
    Description: IAM for AWS Config
    Value: !GetAtt ConfigIAMRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-ROLE-ConfigArn
  BackupIAMArn:
    Description: IAM for AWS Backup
    Value: !GetAtt BackupIAMrole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-ROLE-BackupArn